### ISSUE TITLE
Allow creating contexts from Python objects

### ISSUE THREAD

**Issue by rick2600** [bblfsh/python-client#173]
It would be useful if we could get the python dict from a node, change it and then reload the node with the change to use .filter().

Something like:

```
context = client.parse(filename)
modified_dict = rename_variables(context.root.get())
context.load(modified_dict)
```

**Comment by dennwc** [comment]
From an implementation perspective, we already have this functionality in `libuast` and `pyuast` wrapper. The only missing piece is the client-facing wrapper for it.

I propose something like this:

```python
# context owned by libuast
ctx = client.parse(filename)

# load to Python
ast = ctx.root.get()
modified_dict = rename_variables(ast)

# context owned by Python
ctx = bblfsh.context(modified_dict)
... = ctx.filter("//uast:Identifier")
```

**Comment by bzz** [comment]
This will also enable us to add a [unit test](https://src-d.slack.com/archives/C7UDG9VNY/p1564573857066700?thread_ts=1564572181.064200&cid=C7UDG9VNY) for a case that is missing right now and was not part of the #159 as this is pre-request for having it.

With the logic of:
 - parse a file, load to Python
 - create new python-side context
 - encode loaded UAST using that context
 - compare resulting bytes with `PareseResponse.uast`
