### ISSUE TITLE
Kernel dies when running from jupyter notebook?

### ISSUE THREAD

**Issue by alonsopg** [bblfsh/python-client#184]
After installing babel fish, when I run the library, I get: `The kernel appears to have died. It will restart automatically`. Is this normal? However, when running on the terminal I get a dictionary with the UAST tags, how can I run this client it in python's jupyter notebooks?

**Comment by bzz** [comment]
Hey @alonsopg - yes, one should be able to use it from Jupyter. 

If you could you please also post the python/jupyter/python-client versions that you are having an issue with?

**Comment by alonsopg** [comment]
I reinstalled everything and now works properly, thanks!
