### ISSUE TITLE
What is the difference between a regular AST and the UAST?

### ISSUE THREAD

**Issue by alonsopg** [bblfsh/python-client#186]
Let's say that I have one python AST extracted with the ast library, and a UAST extracted with bblfish. What are the differences between them? Do I lose representation and the ability of modelling a piece of code if I use UAST?

**Comment by kuba--** [comment]
Take a look here: https://forum.sourced.tech/t/difference-between-uast-modes-native-annotated-semantic/69

And bblfsh documentation: https://doc.bblf.sh/uast/uast-specification-v2.html

I hope it can answer your questions

**Comment by alonsopg** [comment]
Great, thanks a lot!
